### ISSUE TITLE
catkin_make --pkg sg-slam错误

### ISSUE THREAD

**Issue by QQQ300kuai** [silencht/SG-SLAM#16]
错误如下，请问应该如何解决

/home/slam/SG-SLAM/src/sg-slam/src/PointcloudMapping.cc: In constructor ‘PointCloudMapping::PointCloudMapping(int, int, int, float, float, int, double, float, int, double, float, int, double, float, float, int, int, float, int)’:
/home/slam/SG-SLAM/src/sg-slam/src/PointcloudMapping.cc:23:80: error: no match for ‘operator=’ (operand types are ‘pcl::PointCloud<pcl::PointXYZRGB>::Ptr’ {aka ‘std::shared_ptr<pcl::PointCloud<pcl::PointXYZRGB> >’} and ‘boost::detail::sp_if_not_array<pcl::PointCloud<pcl::PointXYZRGB> >::type’ {aka ‘boost::shared_ptr<pcl::PointCloud<pcl::PointXYZRGB> >’})
   23 |     semantic_objMap = boost::make_shared< pcl::PointCloud<pcl::PointXYZRGB> >( );
      |                                                                                ^
In file included from /usr/include/c++/9/memory:81,
                 from /usr/include/c++/9/thread:39,
                 from /home/slam/SG-SLAM/src/sg-slam/include/System.h:26,
                 from /home/slam/SG-SLAM/src/sg-slam/include/PointcloudMapping.h:55,
                 from /home/slam/SG-SLAM/src/sg-slam/src/PointcloudMapping.cc:1:
/usr/include/c++/9/bits/shared_ptr.h:309:19: note: candidate: ‘std::shared_ptr<_Tp>& std::shared_ptr<_Tp>::operator=(const std::shared_ptr<_Tp>&) [with _Tp = pcl::PointCloud<pcl::PointXYZRGB>]’
  309 |       shared_ptr& operator=(const shared_ptr&) noexcept = default;
      |                   ^~~~~~~~
/usr/include/c++/9/bits/shared_ptr.h:309:29: note:   no known conversion for argument 1 from ‘boost::detail::sp_if_not_array<pcl::PointCloud<pcl::PointXYZRGB> >::type’ {aka ‘boost::shared_ptr<pcl::PointCloud<pcl::PointXYZRGB> >’} to ‘const std::shared_ptr<pcl::PointCloud<pcl::PointXYZRGB> >&’
  309 |       shared_ptr& operator=(const shared_ptr&) noexcept = default;
      |                             ^~~~~~~~~~~~~~~~~
/usr/include/c++/9/bits/shared_ptr.h:313:2: note: candidate: ‘template<class _Yp> std::shared_ptr<_Tp>::_Assignable<const std::shared_ptr<_Yp>&> std::shared_ptr<_Tp>::operator=(const std::shared_ptr<_Yp>&) [with _Yp = _Yp; _Tp = pcl::PointCloud<pcl::PointXYZRGB>]’
  313 |  operator=(const shared_ptr<_Yp>& __r) noexcept
      |  ^~~~~~~~
/usr/include/c++/9/bits/shared_ptr.h:313:2: note:   template argument deduction/substitution failed:
/home/slam/SG-SLAM/src/sg-slam/src/PointcloudMapping.cc:23:80: note:   ‘boost::detail::sp_if_not_array<pcl::PointCloud<pcl::PointXYZRGB> >::type’ {aka ‘boost::shared_ptr<pcl::PointCloud<pcl::PointXYZRGB> >’} is not derived from ‘const std::shared_ptr<_Tp>’
   23 |     semantic_objMap = boost::make_shared< pcl::PointCloud<pcl::PointXYZRGB> >( );
      |                                                                                ^
In file included from /usr/include/c++/9/memory:81,
                 from /usr/include/c++/9/thread:39,
                 from /home/slam/SG-SLAM/src/sg-slam/include/System.h:26,
                 from /home/slam/SG-SLAM/src/sg-slam/include/PointcloudMapping.h:55,
                 from /home/slam/SG-SLAM/src/sg-slam/src/PointcloudMapping.cc:1:
/usr/include/c++/9/bits/shared_ptr.h:324:2: note: candidate: ‘template<class _Yp> std::shared_ptr<_Tp>::_Assignable<std::auto_ptr<_Up> > std::shared_ptr<_Tp>::operator=(std::auto_ptr<_Up>&&) [with _Yp = _Yp; _Tp = pcl::PointCloud<pcl::PointXYZRGB>]’
  324 |  operator=(auto_ptr<_Yp>&& __r)
      |  ^~~~~~~~
/usr/include/c++/9/bits/shared_ptr.h:324:2: note:   template argument deduction/substitution failed:
/home/slam/SG-SLAM/src/sg-slam/src/PointcloudMapping.cc:23:80: note:   ‘boost::detail::sp_if_not_array<pcl::PointCloud<pcl::PointXYZRGB> >::type’ {aka ‘boost::shared_ptr<pcl::PointCloud<pcl::PointXYZRGB> >’} is not derived from ‘std::auto_ptr<_Up>’
   23 |     semantic_objMap = boost::make_shared< pcl::PointCloud<pcl::PointXYZRGB> >( );
      |                                                                                ^
In file included from /usr/include/c++/9/memory:81,
                 from /usr/include/c++/9/thread:39,
                 from /home/slam/SG-SLAM/src/sg-slam/include/System.h:26,
                 from /home/slam/SG-SLAM/src/sg-slam/include/PointcloudMapping.h:55,
                 from /home/slam/SG-SLAM/src/sg-slam/src/PointcloudMapping.cc:1:
/usr/include/c++/9/bits/shared_ptr.h:333:7: note: candidate: ‘std::shared_ptr<_Tp>& std::shared_ptr<_Tp>::operator=(std::shared_ptr<_Tp>&&) [with _Tp = pcl::PointCloud<pcl::PointXYZRGB>]’
  333 |       operator=(shared_ptr&& __r) noexcept
      |       ^~~~~~~~
/usr/include/c++/9/bits/shared_ptr.h:333:30: note:   no known conversion for argument 1 from ‘boost::detail::sp_if_not_array<pcl::PointCloud<pcl::PointXYZRGB> >::type’ {aka ‘boost::shared_ptr<pcl::PointCloud<pcl::PointXYZRGB> >’} to ‘std::shared_ptr<pcl::PointCloud<pcl::PointXYZRGB> >&&’
  333 |       operator=(shared_ptr&& __r) noexcept
      |                 ~~~~~~~~~~~~~^~~
/usr/include/c++/9/bits/shared_ptr.h:341:2: note: candidate: ‘template<class _Yp> std::shared_ptr<_Tp>::_Assignable<std::shared_ptr<_Yp> > std::shared_ptr<_Tp>::operator=(std::shared_ptr<_Yp>&&) [with _Yp = _Yp; _Tp = pcl::PointCloud<pcl::PointXYZRGB>]’
  341 |  operator=(shared_ptr<_Yp>&& __r) noexcept
      |  ^~~~~~~~
/usr/include/c++/9/bits/shared_ptr.h:341:2: note:   template argument deduction/substitution failed:
/home/slam/SG-SLAM/src/sg-slam/src/PointcloudMapping.cc:23:80: note:   ‘boost::detail::sp_if_not_array<pcl::PointCloud<pcl::PointXYZRGB> >::type’ {aka ‘boost::shared_ptr<pcl::PointCloud<pcl::PointXYZRGB> >’} is not derived from ‘std::shared_ptr<_Tp>’
   23 |     semantic_objMap = boost::make_shared< pcl::PointCloud<pcl::PointXYZRGB> >( );
      |                                                                                ^
In file included from /usr/include/c++/9/memory:81,
                 from /usr/include/c++/9/thread:39,
                 from /home/slam/SG-SLAM/src/sg-slam/include/System.h:26,
                 from /home/slam/SG-SLAM/src/sg-slam/include/PointcloudMapping.h:55,
                 from /home/slam/SG-SLAM/src/sg-slam/src/PointcloudMapping.cc:1:
/usr/include/c++/9/bits/shared_ptr.h:349:2: note: candidate: ‘template<class _Yp, class _Del> std::shared_ptr<_Tp>::_Assignable<std::unique_ptr<_Up, _Ep> > std::shared_ptr<_Tp>::operator=(std::unique_ptr<_Up, _Ep>&&) [with _Yp = _Yp; _Del = _Del; _Tp = pcl::PointCloud<pcl::PointXYZRGB>]’
  349 |  operator=(unique_ptr<_Yp, _Del>&& __r)
      |  ^~~~~~~~
/usr/include/c++/9/bits/shared_ptr.h:349:2: note:   template argument deduction/substitution failed:
/home/slam/SG-SLAM/src/sg-slam/src/PointcloudMapping.cc:23:80: note:   ‘boost::detail::sp_if_not_array<pcl::PointCloud<pcl::PointXYZRGB> >::type’ {aka ‘boost::shared_ptr<pcl::PointCloud<pcl::PointXYZRGB> >’} is not derived from ‘std::unique_ptr<_Tp, _Dp>’
   23 |     semantic_objMap = boost::make_shared< pcl::PointCloud<pcl::PointXYZRGB> >( );
      |                                                                                ^
/home/slam/SG-SLAM/src/sg-slam/src/PointcloudMapping.cc:24:80: error: no match for ‘operator=’ (operand types are ‘pcl::PointCloud<pcl::PointXYZRGB>::Ptr’ {aka ‘std::shared_ptr<pcl::PointCloud<pcl::PointXYZRGB> >’} and ‘boost::detail::sp_if_not_array<pcl::PointCloud<pcl::PointXYZRGB> >::type’ {aka ‘boost::shared_ptr<pcl::PointCloud<pcl::PointXYZRGB> >’})
   24 |     localMap        = boost::make_shared< pcl::PointCloud<pcl::PointXYZRGB> >( );
      |                                                                                ^
In file included from /usr/include/c++/9/memory:81,
                 from /usr/include/c++/9/thread:39,
                 from /home/slam/SG-SLAM/src/sg-slam/include/System.h:26,
                 from /home/slam/SG-SLAM/src/sg-slam/include/PointcloudMapping.h:55,
                 from /home/slam/SG-SLAM/src/sg-slam/src/PointcloudMapping.cc:1:
/usr/include/c++/9/bits/shared_ptr.h:309:19: note: candidate: ‘std::shared_ptr<_Tp>& std::shared_ptr<_Tp>::operator=(const std::shared_ptr<_Tp>&) [with _Tp = pcl::PointCloud<pcl::PointXYZRGB>]’
  309 |       shared_ptr& operator=(const shared_ptr&) noexcept = default;
      |                   ^~~~~~~~
/usr/include/c++/9/bits/shared_ptr.h:309:29: note:   no known conversion for argument 1 from ‘boost::detail::sp_if_not_array<pcl::PointCloud<pcl::PointXYZRGB> >::type’ {aka ‘boost::shared_ptr<pcl::PointCloud<pcl::PointXYZRGB> >’} to ‘const std::shared_ptr<pcl::PointCloud<pcl::PointXYZRGB> >&’
  309 |       shared_ptr& operator=(const shared_ptr&) noexcept = default;
      |                             ^~~~~~~~~~~~~~~~~
/usr/include/c++/9/bits/shared_ptr.h:313:2: note: candidate: ‘template<class _Yp> std::shared_ptr<_Tp>::_Assignable<const std::shared_ptr<_Yp>&> std::shared_ptr<_Tp>::operator=(const std::shared_ptr<_Yp>&) [with _Yp = _Yp; _Tp = pcl::PointCloud<pcl::PointXYZRGB>]’
  313 |  operator=(const shared_ptr<_Yp>& __r) noexcept
      |  ^~~~~~~~
/usr/include/c++/9/bits/shared_ptr.h:313:2: note:   template argument deduction/substitution failed:
/home/slam/SG-SLAM/src/sg-slam/src/PointcloudMapping.cc:24:80: note:   ‘boost::detail::sp_if_not_array<pcl::PointCloud<pcl::PointXYZRGB> >::type’ {aka ‘boost::shared_ptr<pcl::PointCloud<pcl::PointXYZRGB> >’} is not derived from ‘const std::shared_ptr<_Tp>’
   24 |     localMap        = boost::make_shared< pcl::PointCloud<pcl::PointXYZRGB> >( );
      |                                                                                ^
In file included from /usr/include/c++/9/memory:81,
                 from /usr/include/c++/9/thread:39,
                 from /home/slam/SG-SLAM/src/sg-slam/include/System.h:26,
                 from /home/slam/SG-SLAM/src/sg-slam/include/PointcloudMapping.h:55,
                 from /home/slam/SG-SLAM/src/sg-slam/src/PointcloudMapping.cc:1:
/usr/include/c++/9/bits/shared_ptr.h:324:2: note: candidate: ‘template<class _Yp> std::shared_ptr<_Tp>::_Assignable<std::auto_ptr<_Up> > std::shared_ptr<_Tp>::operator=(std::auto_ptr<_Up>&&) [with _Yp = _Yp; _Tp = pcl::PointCloud<pcl::PointXYZRGB>]’
  324 |  operator=(auto_ptr<_Yp>&& __r)
      |  ^~~~~~~~
/usr/include/c++/9/bits/shared_ptr.h:324:2: note:   template argument deduction/substitution failed:
/home/slam/SG-SLAM/src/sg-slam/src/PointcloudMapping.cc:24:80: note:   ‘boost::detail::sp_if_not_array<pcl::PointCloud<pcl::PointXYZRGB> >::type’ {aka ‘boost::shared_ptr<pcl::PointCloud<pcl::PointXYZRGB> >’} is not derived from ‘std::auto_ptr<_Up>’
   24 |     localMap        = boost::make_shared< pcl::PointCloud<pcl::PointXYZRGB> >( );
      |                                                                                ^
In file included from /usr/include/c++/9/memory:81,
                 from /usr/include/c++/9/thread:39,
                 from /home/slam/SG-SLAM/src/sg-slam/include/System.h:26,
                 from /home/slam/SG-SLAM/src/sg-slam/include/PointcloudMapping.h:55,
                 from /home/slam/SG-SLAM/src/sg-slam/src/PointcloudMapping.cc:1:
/usr/include/c++/9/bits/shared_ptr.h:333:7: note: candidate: ‘std::shared_ptr<_Tp>& std::shared_ptr<_Tp>::operator=(std::shared_ptr<_Tp>&&) [with _Tp = pcl::PointCloud<pcl::PointXYZRGB>]’
  333 |       operator=(shared_ptr&& __r) noexcept
      |       ^~~~~~~~
/usr/include/c++/9/bits/shared_ptr.h:333:30: note:   no known conversion for argument 1 from ‘boost::detail::sp_if_not_array<pcl::PointCloud<pcl::PointXYZRGB> >::type’ {aka ‘boost::shared_ptr<pcl::PointCloud<pcl::PointXYZRGB> >’} to ‘std::shared_ptr<pcl::PointCloud<pcl::PointXYZRGB> >&&’
  333 |       operator=(shared_ptr&& __r) noexcept
      |                 ~~~~~~~~~~~~~^~~
/usr/include/c++/9/bits/shared_ptr.h:341:2: note: candidate: ‘template<class _Yp> std::shared_ptr<_Tp>::_Assignable<std::shared_ptr<_Yp> > std::shared_ptr<_Tp>::operator=(std::shared_ptr<_Yp>&&) [with _Yp = _Yp; _Tp = pcl::PointCloud<pcl::PointXYZRGB>]’
  341 |  operator=(shared_ptr<_Yp>&& __r) noexcept
      |  ^~~~~~~~
/usr/include/c++/9/bits/shared_ptr.h:341:2: note:   template argument deduction/substitution failed:
/home/slam/SG-SLAM/src/sg-slam/src/PointcloudMapping.cc:24:80: note:   ‘boost::detail::sp_if_not_array<pcl::PointCloud<pcl::PointXYZRGB> >::type’ {aka ‘boost::shared_ptr<pcl::PointCloud<pcl::PointXYZRGB> >’} is not derived from ‘std::shared_ptr<_Tp>’
   24 |     localMap        = boost::make_shared< pcl::PointCloud<pcl::PointXYZRGB> >( );
      |                                                                                ^
In file included from /usr/include/c++/9/memory:81,
                 from /usr/include/c++/9/thread:39,
                 from /home/slam/SG-SLAM/src/sg-slam/include/System.h:26,
                 from /home/slam/SG-SLAM/src/sg-slam/include/PointcloudMapping.h:55,
                 from /home/slam/SG-SLAM/src/sg-slam/src/PointcloudMapping.cc:1:
/usr/include/c++/9/bits/shared_ptr.h:349:2: note: candidate: ‘template<class _Yp, class _Del> std::shared_ptr<_Tp>::_Assignable<std::unique_ptr<_Up, _Ep> > std::shared_ptr<_Tp>::operator=(std::unique_ptr<_Up, _Ep>&&) [with _Yp = _Yp; _Del = _Del; _Tp = pcl::PointCloud<pcl::PointXYZRGB>]’
  349 |  operator=(unique_ptr<_Yp, _Del>&& __r)
      |  ^~~~~~~~
/usr/include/c++/9/bits/shared_ptr.h:349:2: note:   template argument deduction/substitution failed:
/home/slam/SG-SLAM/src/sg-slam/src/PointcloudMapping.cc:24:80: note:   ‘boost::detail::sp_if_not_array<pcl::PointCloud<pcl::PointXYZRGB> >::type’ {aka ‘boost::shared_ptr<pcl::PointCloud<pcl::PointXYZRGB> >’} is not derived from ‘std::unique_ptr<_Tp, _Dp>’
   24 |     localMap        = boost::make_shared< pcl::PointCloud<pcl::PointXYZRGB> >( );
      |                                                                                ^
/home/slam/SG-SLAM/src/sg-slam/src/PointcloudMapping.cc:25:80: error: no match for ‘operator=’ (operand types are ‘pcl::PointCloud<pcl::PointXYZRGB>::Ptr’ {aka ‘std::shared_ptr<pcl::PointCloud<pcl::PointXYZRGB> >’} and ‘boost::detail::sp_if_not_array<pcl::PointCloud<pcl::PointXYZRGB> >::type’ {aka ‘boost::shared_ptr<pcl::PointCloud<pcl::PointXYZRGB> >’})
   25 |     temp_globalMap  = boost::make_shared< pcl::PointCloud<pcl::PointXYZRGB> >( );
      |                                                                                ^
In file included from /usr/include/c++/9/memory:81,
                 from /usr/include/c++/9/thread:39,
                 from /home/slam/SG-SLAM/src/sg-slam/include/System.h:26,
                 from /home/slam/SG-SLAM/src/sg-slam/include/PointcloudMapping.h:55,
                 from /home/slam/SG-SLAM/src/sg-slam/src/PointcloudMapping.cc:1:
/usr/include/c++/9/bits/shared_ptr.h:309:19: note: candidate: ‘std::shared_ptr<_Tp>& std::shared_ptr<_Tp>::operator=(const std::shared_ptr<_Tp>&) [with _Tp = pcl::PointCloud<pcl::PointXYZRGB>]’
  309 |       shared_ptr& operator=(const shared_ptr&) noexcept = default;
      |                   ^~~~~~~~
/usr/include/c++/9/bits/shared_ptr.h:309:29: note:   no known conversion for argument 1 from ‘boost::detail::sp_if_not_array<pcl::PointCloud<pcl::PointXYZRGB> >::type’ {aka ‘boost::shared_ptr<pcl::PointCloud<pcl::PointXYZRGB> >’} to ‘const std::shared_ptr<pcl::PointCloud<pcl::PointXYZRGB> >&’
  309 |       shared_ptr& operator=(const shared_ptr&) noexcept = default;
      |                             ^~~~~~~~~~~~~~~~~
/usr/include/c++/9/bits/shared_ptr.h:313:2: note: candidate: ‘template<class _Yp> std::shared_ptr<_Tp>::_Assignable<const std::shared_ptr<_Yp>&> std::shared_ptr<_Tp>::operator=(const std::shared_ptr<_Yp>&) [with _Yp = _Yp; _Tp = pcl::PointCloud<pcl::PointXYZRGB>]’
  313 |  operator=(const shared_ptr<_Yp>& __r) noexcept
      |  ^~~~~~~~
/usr/include/c++/9/bits/shared_ptr.h:313:2: note:   template argument deduction/substitution failed:
/home/slam/SG-SLAM/src/sg-slam/src/PointcloudMapping.cc:25:80: note:   ‘boost::detail::sp_if_not_array<pcl::PointCloud<pcl::PointXYZRGB> >::type’ {aka ‘boost::shared_ptr<pcl::PointCloud<pcl::PointXYZRGB> >’} is not derived from ‘const std::shared_ptr<_Tp>’
   25 |     temp_globalMap  = boost::make_shared< pcl::PointCloud<pcl::PointXYZRGB> >( );
      |                                                                                ^
In file included from /usr/include/c++/9/memory:81,
                 from /usr/include/c++/9/thread:39,
                 from /home/slam/SG-SLAM/src/sg-slam/include/System.h:26,
                 from /home/slam/SG-SLAM/src/sg-slam/include/PointcloudMapping.h:55,
                 from /home/slam/SG-SLAM/src/sg-slam/src/PointcloudMapping.cc:1:
/usr/include/c++/9/bits/shared_ptr.h:324:2: note: candidate: ‘template<class _Yp> std::shared_ptr<_Tp>::_Assignable<std::auto_ptr<_Up> > std::shared_ptr<_Tp>::operator=(std::auto_ptr<_Up>&&) [with _Yp = _Yp; _Tp = pcl::PointCloud<pcl::PointXYZRGB>]’
  324 |  operator=(auto_ptr<_Yp>&& __r)
      |  ^~~~~~~~
/usr/include/c++/9/bits/shared_ptr.h:324:2: note:   template argument deduction/substitution failed:
/home/slam/SG-SLAM/src/sg-slam/src/PointcloudMapping.cc:25:80: note:   ‘boost::detail::sp_if_not_array<pcl::PointCloud<pcl::PointXYZRGB> >::type’ {aka ‘boost::shared_ptr<pcl::PointCloud<pcl::PointXYZRGB> >’} is not derived from ‘std::auto_ptr<_Up>’
   25 |     temp_globalMap  = boost::make_shared< pcl::PointCloud<pcl::PointXYZRGB> >( );
      |                                                                                ^
In file included from /usr/include/c++/9/memory:81,
                 from /usr/include/c++/9/thread:39,
                 from /home/slam/SG-SLAM/src/sg-slam/include/System.h:26,
                 from /home/slam/SG-SLAM/src/sg-slam/include/PointcloudMapping.h:55,
                 from /home/slam/SG-SLAM/src/sg-slam/src/PointcloudMapping.cc:1:
/usr/include/c++/9/bits/shared_ptr.h:333:7: note: candidate: ‘std::shared_ptr<_Tp>& std::shared_ptr<_Tp>::operator=(std::shared_ptr<_Tp>&&) [with _Tp = pcl::PointCloud<pcl::PointXYZRGB>]’
  333 |       operator=(shared_ptr&& __r) noexcept
      |       ^~~~~~~~
/usr/include/c++/9/bits/shared_ptr.h:333:30: note:   no known conversion for argument 1 from ‘boost::detail::sp_if_not_array<pcl::PointCloud<pcl::PointXYZRGB> >::type’ {aka ‘boost::shared_ptr<pcl::PointCloud<pcl::PointXYZRGB> >’} to ‘std::shared_ptr<pcl::PointCloud<pcl::PointXYZRGB> >&&’
  333 |       operator=(shared_ptr&& __r) noexcept
      |                 ~~~~~~~~~~~~~^~~
/usr/include/c++/9/bits/shared_ptr.h:341:2: note: candidate: ‘template<class _Yp> std::shared_ptr<_Tp>::_Assignable<std::shared_ptr<_Yp> > std::shared_ptr<_Tp>::operator=(std::shared_ptr<_Yp>&&) [with _Yp = _Yp; _Tp = pcl::PointCloud<pcl::PointXYZRGB>]’
  341 |  operator=(shared_ptr<_Yp>&& __r) noexcept
      |  ^~~~~~~~
/usr/include/c++/9/bits/shared_ptr.h:341:2: note:   template argument deduction/substitution failed:
/home/slam/SG-SLAM/src/sg-slam/src/PointcloudMapping.cc:25:80: note:   ‘boost::detail::sp_if_not_array<pcl::PointCloud<pcl::PointXYZRGB> >::type’ {aka ‘boost::shared_ptr<pcl::PointCloud<pcl::PointXYZRGB> >’} is not derived from ‘std::shared_ptr<_Tp>’
   25 |     temp_globalMap  = boost::make_shared< pcl::PointCloud<pcl::PointXYZRGB> >( );
      |                                                                                ^
In file included from /usr/include/c++/9/memory:81,
                 from /usr/include/c++/9/thread:39,
                 from /home/slam/SG-SLAM/src/sg-slam/include/System.h:26,
                 from /home/slam/SG-SLAM/src/sg-slam/include/PointcloudMapping.h:55,
                 from /home/slam/SG-SLAM/src/sg-slam/src/PointcloudMapping.cc:1:
/usr/include/c++/9/bits/shared_ptr.h:349:2: note: candidate: ‘template<class _Yp, class _Del> std::shared_ptr<_Tp>::_Assignable<std::unique_ptr<_Up, _Ep> > std::shared_ptr<_Tp>::operator=(std::unique_ptr<_Up, _Ep>&&) [with _Yp = _Yp; _Del = _Del; _Tp = pcl::PointCloud<pcl::PointXYZRGB>]’
  349 |  operator=(unique_ptr<_Yp, _Del>&& __r)
      |  ^~~~~~~~
/usr/include/c++/9/bits/shared_ptr.h:349:2: note:   template argument deduction/substitution failed:
/home/slam/SG-SLAM/src/sg-slam/src/PointcloudMapping.cc:25:80: note:   ‘boost::detail::sp_if_not_array<pcl::PointCloud<pcl::PointXYZRGB> >::type’ {aka ‘boost::shared_ptr<pcl::PointCloud<pcl::PointXYZRGB> >’} is not derived from ‘std::unique_ptr<_Tp, _Dp>’
   25 |     temp_globalMap  = boost::make_shared< pcl::PointCloud<pcl::PointXYZRGB> >( );
      |                                                                                ^
/home/slam/SG-SLAM/src/sg-slam/src/PointcloudMapping.cc:29:79: error: no match for ‘operator=’ (operand types are ‘pcl::PointCloud<pcl::PointXYZRGB>::Ptr’ {aka ‘std::shared_ptr<pcl::PointCloud<pcl::PointXYZRGB> >’} and ‘boost::detail::sp_if_not_array<pcl::PointCloud<pcl::PointXYZRGB> >::type’ {aka ‘boost::shared_ptr<pcl::PointCloud<pcl::PointXYZRGB> >’})
   29 |         globalMap  = boost::make_shared< pcl::PointCloud<pcl::PointXYZRGB> >( );
      |                                                                               ^
In file included from /usr/include/c++/9/memory:81,
                 from /usr/include/c++/9/thread:39,
                 from /home/slam/SG-SLAM/src/sg-slam/include/System.h:26,
                 from /home/slam/SG-SLAM/src/sg-slam/include/PointcloudMapping.h:55,
                 from /home/slam/SG-SLAM/src/sg-slam/src/PointcloudMapping.cc:1:
/usr/include/c++/9/bits/shared_ptr.h:309:19: note: candidate: ‘std::shared_ptr<_Tp>& std::shared_ptr<_Tp>::operator=(const std::shared_ptr<_Tp>&) [with _Tp = pcl::PointCloud<pcl::PointXYZRGB>]’
  309 |       shared_ptr& operator=(const shared_ptr&) noexcept = default;
      |                   ^~~~~~~~
/usr/include/c++/9/bits/shared_ptr.h:309:29: note:   no known conversion for argument 1 from ‘boost::detail::sp_if_not_array<pcl::PointCloud<pcl::PointXYZRGB> >::type’ {aka ‘boost::shared_ptr<pcl::PointCloud<pcl::PointXYZRGB> >’} to ‘const std::shared_ptr<pcl::PointCloud<pcl::PointXYZRGB> >&’
  309 |       shared_ptr& operator=(const shared_ptr&) noexcept = default;
      |                             ^~~~~~~~~~~~~~~~~
/usr/include/c++/9/bits/shared_ptr.h:313:2: note: candidate: ‘template<class _Yp> std::shared_ptr<_Tp>::_Assignable<const std::shared_ptr<_Yp>&> std::shared_ptr<_Tp>::operator=(const std::shared_ptr<_Yp>&) [with _Yp = _Yp; _Tp = pcl::PointCloud<pcl::PointXYZRGB>]’
  313 |  operator=(const shared_ptr<_Yp>& __r) noexcept
      |  ^~~~~~~~
/usr/include/c++/9/bits/shared_ptr.h:313:2: note:   template argument deduction/substitution failed:
/home/slam/SG-SLAM/src/sg-slam/src/PointcloudMapping.cc:29:79: note:   ‘boost::detail::sp_if_not_array<pcl::PointCloud<pcl::PointXYZRGB> >::type’ {aka ‘boost::shared_ptr<pcl::PointCloud<pcl::PointXYZRGB> >’} is not derived from ‘const std::shared_ptr<_Tp>’
   29 |         globalMap  = boost::make_shared< pcl::PointCloud<pcl::PointXYZRGB> >( );
      |                                                                               ^
In file included from /usr/include/c++/9/memory:81,
                 from /usr/include/c++/9/thread:39,
                 from /home/slam/SG-SLAM/src/sg-slam/include/System.h:26,
                 from /home/slam/SG-SLAM/src/sg-slam/include/PointcloudMapping.h:55,
                 from /home/slam/SG-SLAM/src/sg-slam/src/PointcloudMapping.cc:1:
/usr/include/c++/9/bits/shared_ptr.h:324:2: note: candidate: ‘template<class _Yp> std::shared_ptr<_Tp>::_Assignable<std::auto_ptr<_Up> > std::shared_ptr<_Tp>::operator=(std::auto_ptr<_Up>&&) [with _Yp = _Yp; _Tp = pcl::PointCloud<pcl::PointXYZRGB>]’
  324 |  operator=(auto_ptr<_Yp>&& __r)
      |  ^~~~~~~~
/usr/include/c++/9/bits/shared_ptr.h:324:2: note:   template argument deduction/substitution failed:
/home/slam/SG-SLAM/src/sg-slam/src/PointcloudMapping.cc:29:79: note:   ‘boost::detail::sp_if_not_array<pcl::PointCloud<pcl::PointXYZRGB> >::type’ {aka ‘boost::shared_ptr<pcl::PointCloud<pcl::PointXYZRGB> >’} is not derived from ‘std::auto_ptr<_Up>’
   29 |         globalMap  = boost::make_shared< pcl::PointCloud<pcl::PointXYZRGB> >( );
      |                                                                               ^
In file included from /usr/include/c++/9/memory:81,
                 from /usr/include/c++/9/thread:39,
                 from /home/slam/SG-SLAM/src/sg-slam/include/System.h:26,
                 from /home/slam/SG-SLAM/src/sg-slam/include/PointcloudMapping.h:55,
                 from /home/slam/SG-SLAM/src/sg-slam/src/PointcloudMapping.cc:1:
/usr/include/c++/9/bits/shared_ptr.h:333:7: note: candidate: ‘std::shared_ptr<_Tp>& std::shared_ptr<_Tp>::operator=(std::shared_ptr<_Tp>&&) [with _Tp = pcl::PointCloud<pcl::PointXYZRGB>]’
  333 |       operator=(shared_ptr&& __r) noexcept
      |       ^~~~~~~~
/usr/include/c++/9/bits/shared_ptr.h:333:30: note:   no known conversion for argument 1 from ‘boost::detail::sp_if_not_array<pcl::PointCloud<pcl::PointXYZRGB> >::type’ {aka ‘boost::shared_ptr<pcl::PointCloud<pcl::PointXYZRGB> >’} to ‘std::shared_ptr<pcl::PointCloud<pcl::PointXYZRGB> >&&’
  333 |       operator=(shared_ptr&& __r) noexcept
      |                 ~~~~~~~~~~~~~^~~
/usr/include/c++/9/bits/shared_ptr.h:341:2: note: candidate: ‘template<class _Yp> std::shared_ptr<_Tp>::_Assignable<std::shared_ptr<_Yp> > std::shared_ptr<_Tp>::operator=(std::shared_ptr<_Yp>&&) [with _Yp = _Yp; _Tp = pcl::PointCloud<pcl::PointXYZRGB>]’
  341 |  operator=(shared_ptr<_Yp>&& __r) noexcept
      |  ^~~~~~~~
/usr/include/c++/9/bits/shared_ptr.h:341:2: note:   template argument deduction/substitution failed:
/home/slam/SG-SLAM/src/sg-slam/src/PointcloudMapping.cc:29:79: note:   ‘boost::detail::sp_if_not_array<pcl::PointCloud<pcl::PointXYZRGB> >::type’ {aka ‘boost::shared_ptr<pcl::PointCloud<pcl::PointXYZRGB> >’} is not derived from ‘std::shared_ptr<_Tp>’
   29 |         globalMap  = boost::make_shared< pcl::PointCloud<pcl::PointXYZRGB> >( );
      |                                                                               ^
In file included from /usr/include/c++/9/memory:81,
                 from /usr/include/c++/9/thread:39,
                 from /home/slam/SG-SLAM/src/sg-slam/include/System.h:26,
                 from /home/slam/SG-SLAM/src/sg-slam/include/PointcloudMapping.h:55,
                 from /home/slam/SG-SLAM/src/sg-slam/src/PointcloudMapping.cc:1:
/usr/include/c++/9/bits/shared_ptr.h:349:2: note: candidate: ‘template<class _Yp, class _Del> std::shared_ptr<_Tp>::_Assignable<std::unique_ptr<_Up, _Ep> > std::shared_ptr<_Tp>::operator=(std::unique_ptr<_Up, _Ep>&&) [with _Yp = _Yp; _Del = _Del; _Tp = pcl::PointCloud<pcl::PointXYZRGB>]’
  349 |  operator=(unique_ptr<_Yp, _Del>&& __r)
      |  ^~~~~~~~
/usr/include/c++/9/bits/shared_ptr.h:349:2: note:   template argument deduction/substitution failed:
/home/slam/SG-SLAM/src/sg-slam/src/PointcloudMapping.cc:29:79: note:   ‘boost::detail::sp_if_not_array<pcl::PointCloud<pcl::PointXYZRGB> >::type’ {aka ‘boost::shared_ptr<pcl::PointCloud<pcl::PointXYZRGB> >’} is not derived from ‘std::unique_ptr<_Tp, _Dp>’
   29 |         globalMap  = boost::make_shared< pcl::PointCloud<pcl::PointXYZRGB> >( );
      |                                                                               ^
make[2]: *** [sg-slam/CMakeFiles/sg-slam.dir/build.make:349：sg-slam/CMakeFiles/sg-slam.dir/src/PointcloudMapping.cc.o] 错误 1
make[2]: *** 正在等待未完成的任务....
make[1]: *** [CMakeFiles/Makefile2:4443：sg-slam/CMakeFiles/sg-slam.dir/all] 错误 2
make: *** [Makefile:141：all] 错误 2
Invoking "make -j16 -l16" failed

**Comment by silencht** [comment]
可以尝试修改智能指针创建方式，由boost库替换为c++标准库
https://github.com/iralabdisco/pso_registration/issues/2#issuecomment-730297899

**Comment by QQQ300kuai** [comment]
在`PointcloudMapping.cc` 中以下位置将boost::make_shared' 更改为 'std::make_shared'，它就可以工作了，谢谢你。我使用的是pcl1.12
```
    semantic_objMap = std::make_shared<pcl::PointCloud<pcl::PointXYZRGB>>();
    localMap = std::make_shared<pcl::PointCloud<pcl::PointXYZRGB>>();
    temp_globalMap = std::make_shared<pcl::PointCloud<pcl::PointXYZRGB>>();
```
