### ISSUE TITLE
为什么无法显示八叉树地图？

### ISSUE THREAD

**Issue by SZUshenyan** [silencht/SG-SLAM#17]
您好，我按照你的提示操作后，可以建立点云地图，也可以建立语义对象度量地图，但是就是建立不了八叉树地图，并且也没有任何报错，请问一下是什么问题？
![Screenshot from 2023-12-04 20-25-27](https://github.com/silencht/SG-SLAM/assets/152782550/5cad1584-2601-47f0-a6e1-ba7868f3b4c6)
![Screenshot from 2023-12-04 20-31-19](https://github.com/silencht/SG-SLAM/assets/152782550/d38fbcff-887a-4e6d-9e49-ae0c590da01e)

**Comment by silencht** [comment]
请先参考一下其他issues中关于octomap使用的问题，或者提供更多终端输出信息？

**Comment by SZUshenyan** [comment]
我已经按照其他的issues也操作了，命令前，运行source devel/setup.bash将当前功能包目录添加到系统变量，但是还是解决不了。下面是我的终端输出信息
![Uploading Screenshot from 2023-12-04 20-43-11.png…]()

**Comment by SZUshenyan** [comment]
sy@zx-System-Product-Name:~/SG-SLAM/src/octomap_server/launch$ roslaunch octomap.launch
... logging to /home/sy/.ros/log/36743d7e-927b-11ee-9554-581122c94a71/roslaunch-zx-System-Product-Name-23155.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://zx-System-Product-Name:45237/

SUMMARY
========

PARAMETERS
 * /octomap_server/base_frame_id: /map
 * /octomap_server/colored_map: True
 * /octomap_server/filter_ground: False
 * /octomap_server/filter_speckles: True
 * /octomap_server/frame_id: /map
 * /octomap_server/ground_filter/angle: 0.15
 * /octomap_server/ground_filter/distance: 0.05
 * /octomap_server/ground_filter/plane_distance: 0.05
 * /octomap_server/height_map: False
 * /octomap_server/latch: False
 * /octomap_server/occupancy_max_z: 1.5
 * /octomap_server/occupancy_min_z: -1.5
 * /octomap_server/pointcloud_max_z: 5.0
 * /octomap_server/pointcloud_min_z: -5.0
 * /octomap_server/resolution: 0.05
 * /octomap_server/sensor_model/hit: 0.7
 * /octomap_server/sensor_model/max: 0.99
 * /octomap_server/sensor_model/max_range: -1.0
 * /octomap_server/sensor_model/min: 0.12
 * /octomap_server/sensor_model/miss: 0.4
 * /rosdistro: melodic
 * /rosversion: 1.14.13

NODES
  /
    octomap_server (octomap_server/octomap_server_node)

ROS_MASTER_URI=http://localhost:11311

process[octomap_server-1]: started with pid [23198]
[ WARN] [1701693748.694816161]: Nothing to publish, octree is empty

**Comment by SZUshenyan** [comment]
sy@zx-System-Product-Name:~$ rviz -d /home/sy/SG-SLAM/src/sg-slam/Examples/rvizconfig.rviz
[ INFO] [1701693759.541288107]: rviz version 1.13.30
[ INFO] [1701693759.541316565]: compiled against Qt version 5.9.5
[ INFO] [1701693759.541325250]: compiled against OGRE version 1.9.0 (Ghadamon)
[ INFO] [1701693759.543163263]: Forcing OpenGl version 0.
[ INFO] [1701693759.866414167]: Stereo is NOT SUPPORTED
[ INFO] [1701693759.866446594]: OpenGL device: NVIDIA GeForce RTX 3090/PCIe/SSE2
[ INFO] [1701693759.866456079]: OpenGl version: 4.6 (GLSL 4.6).

**Comment by SZUshenyan** [comment]
sy@zx-System-Product-Name:~/SG-SLAM/src/sg-slam$ ./run_tum_walking_xyz.sh

ORB-SLAM2 Copyright (C) 2014-2016 Raul Mur-Artal, University of Zaragoza.
This program comes with ABSOLUTELY NO WARRANTY;
This is free software, and you are welcome to redistribute it
under certain conditions. See LICENSE.txt.

Input sensor was set to: RGB-D

Loading ORB Vocabulary. This could take a while...
Vocabulary loaded!


is map construction consider dynamic: 1
is global pointcloud reconstruction: 0
is octomap semanticObject map construction: 1
camera_valid_depth_Min is 0.5
camera_valid_depth_Max is 5
Sor_Local_MeanK is 50
Sor_Local_StddevMulThresh is 3
Voxel_Local_LeafSize is 0.01
Sor_Global_MeanK is 50
Sor_Global_StddevMulThresh is 3
Voxel_Global_LeafSize is 0.01
Detector3D_Sor_MeanK is 50
Detector3D_Sor_StddevMulThresh is 1
Detector3D_Voxel_LeafSize is 0.01
Detect3D_EuclideanClusterTolerance is 0.02
Detect3D_EuclideanClusterMinSize is 1000
Detect3D_EuclideanClusterMaxSize is 30000
Detect3D_DetectSimilarCompareRatio is 0.1
global_pc_update_kf_threshold is 25
Start PointCloudMapping Viewer...

Camera Parameters: 
- fx: 535.4
- fy: 539.2
- cx: 320.1
- cy: 247.6
- k1: 0
- k2: 0
- p1: 0
- p2: 0
- fps: 30
- color order: RGB (ignored if grayscale)

ORB Extractor Parameters: 
- Number of Features: 1000
- Scale Levels: 8
- Scale Factor: 1.2
- Initial Fast Threshold: 20
- Minimum Fast Threshold: 7

Depth Threshold (Close/Far Points): 2.98842

detection_confidence_threshold is 0.9

dynamic_detection_confidence_threshold is 0.01
Detector2D Thread start ...

-------
Start processing sequence ...
Images in the sequence: 827

New map created with 715 points
Gtk-Message: 20:47:59.589: Failed to load module "canberra-gtk-module"

**Comment by SZUshenyan** [comment]
![Uploading Screenshot from 2023-12-04 20-43-11.png…]()

**Comment by silencht** [comment]
奇怪，我从输出信息中没有看出明显的错误。
使用rostopic list和echo等命令查看一下系统是否在正常输出octomap话题数据？

**Comment by SZUshenyan** [comment]
![Screenshot from 2023-12-04 22-29-46](https://github.com/silencht/SG-SLAM/assets/152782550/71faebb3-0cac-4b1e-a499-ace47892306d)

**Comment by SZUshenyan** [comment]
话题输出也是正常的，请问要怎么解决呀

**Comment by SZUshenyan** [comment]
显示八叉树地图是启动rviz，则选择左下角的add，选择by topic，选择occupied_cells_vis_array下的MarkerArray吧？

**Comment by silencht** [comment]
是的呀，rviz已经配置好了。
我的意思是rostopic echo 话题名称 （不是单纯的echo命令😆），看一下数据是否正常。
奇怪，一般来说点云可以显示的话，octomap应该也没问题了。

**Comment by SZUshenyan** [comment]
使用echo命令点云可以正常输出，但是八叉树没有输出

**Comment by silencht** [comment]
通过目前的信息我也无法判断哪里出现了问题，可以尝试一下在octomap相关的代码中打印一些变量的信息辅助判断。

**Comment by SZUshenyan** [comment]
您好，可以加一下联系方式吗？除此之外还想向您请教一下您的这篇文章在室外是否可行？

**Comment by silencht** [comment]
联系方式可在此页面寻找 https://silencht.github.io/about/ 
> 这篇文章在室外是否可行？

这取决于深度相机（输入设备）的特性

**Comment by flowerCamellia** [comment]
为什么我的点云地图是这样的

![Image](https://github.com/user-attachments/assets/77a55330-da38-4a08-ab3b-1a6fed64d9aa)
测试数据集的时候会有一段无法跟踪

**Comment by flowerCamellia** [comment]
跟踪丢失
