### ISSUE TITLE
Evo difference lines

### ISSUE THREAD

**Issue by gyk321** [silencht/SG-SLAM#2]
Just wondering how to make evo difference lines in your paper

**Comment by silencht** [comment]
I may not understand what you are asking. Here's an answer I think might help you?

The trajectory error data and pictures in the paper come from TUM's dataset [evaluation tool](https://cvg.cit.tum.de/data/datasets/rgbd-dataset/tools#evaluation).

Here, when SLAM has finished tracking a dataset sequence, two estimated trajectory files, CameraTrajectory.txt and KeyFrameTrajectory.txt, will be created in the execution directory. Then, the two scripts evaluate_ate.py and evaluate_rpe.py provided by TUM can be used to evaluate these two estimated trajectory files with the truth trajectory groundtruth.txt provided by the dataset. The specific script usage can be found at the above URL as well as many blogs and forums.

I didn't use the [evo repository program](https://github.com/MichaelGrupp/evo) for this work, although evo may draw a nicer picture.
