### ISSUE TITLE
运行./run_tum_walking_xyz.sh无结果

### ISSUE THREAD

**Issue by QQQ300kuai** [silencht/SG-SLAM#20]
你好，运行问题命令为（数据集存放位置改变了）
`./Examples/sg_slam_tum Vocabulary/ORBvoc.bin Examples/TUM3.yaml /home/slam/datasets/rgbd_dataset_freiburg3_walking_xyz_validation /home/slam/datasets/rgbd_dataset_freiburg3_walking_xyz_validation/associations.txt
`

![image](https://github.com/silencht/SG-SLAM/assets/55626566/2018b21e-e4f1-459a-9d3f-9abe0ebef686)

当我直接输入命令运行，也一样无反应

![image](https://github.com/silencht/SG-SLAM/assets/55626566/e2e1a733-aa99-4842-b84f-36c7a3664e93)

**Comment by QQQ300kuai** [comment]
这是我的topic list。有没有什么解决办法，感谢
![image](https://github.com/silencht/SG-SLAM/assets/55626566/beb10c88-b2e6-40ea-b0ce-3c253d52c1fa)

**Comment by silencht** [comment]
如果仅输入 `./Examples/sg_slam_tum`命令会输出Usage: ./rgbd_tum path_to_vocabulary path_to_settings path_to_sequence path_to_association，那么请继续仔细检查后续的参数项

**Comment by QQQ300kuai** [comment]
我重新检查了参数，应该是没问题的。
现在运行显示的是段错误。
![image](https://github.com/silencht/SG-SLAM/assets/55626566/cc75c6f9-5077-4c85-b85a-52eb131844a0)

**Comment by QQQ300kuai** [comment]
我ORB-SLAM3是能正常运行的

**Comment by silencht** [comment]
请使用
```
gdb ./Examples/sg_slam_tum
```
进入调试模式，
然后输入
```
run + 剩余参数（path_to_vocabulary path_to_settings path_to_sequence path_to_association）
```
启动slam。
查看段错误发生位置。产生段错误后，可使用`bt`命令查看回溯函数调用堆栈。
如果堆栈回溯定位不清晰，可在CMakeLists.txt中设置Debug模式，编译程序后，再次进行以上步骤的调试。

**Comment by QQQ300kuai** [comment]
这是显示的结果，可以从哪块入手，解决段错误呢。不太熟悉
![image](https://github.com/silencht/SG-SLAM/assets/55626566/ae87d764-f099-48e7-9c7d-3e2672d521d5)

**Comment by silencht** [comment]
看样子可能是cv::file读取yaml文件读取路径有问题，文件打开失败。

**Comment by QQQ300kuai** [comment]
我查看了，传入yaml文件位置是准确的

**Comment by silencht** [comment]
请检查一下run命令后面的参数是ocabulary是否输入错误（缺少开头v），还是显示问题？

**Comment by QQQ300kuai** [comment]
对 ocabulary缺少了V，修改后，错误信息一样
![image](https://github.com/silencht/SG-SLAM/assets/55626566/713c2475-0dac-484b-be3e-6b75d7e42221)

**Comment by QQQ300kuai** [comment]
CMakeLists.txt中设置Debug模式后，这是更详细的信息
![image](https://github.com/silencht/SG-SLAM/assets/55626566/7e8253d3-af3d-4cde-a7d0-dde97732c8a7)

**Comment by silencht** [comment]
从调试信息来看的话，就是cv::FileStorage::open函数打开参数文件失败。
尝试将所有参数文件路径均替换为全局路径（而非相对路径），并检查路径下文件确实存在，且内容完好？

**Comment by QQQ300kuai** [comment]
将所有参数文件路径均替换为全局路径依旧错误，错误信息一样。文件内容也是完好的

在代码62行中，发生段错误。
![image](https://github.com/silencht/SG-SLAM/assets/55626566/0a703d08-0252-4569-8cf6-65cddbf3b2cb)

我重新测试了62行这段打开文件代码，是能正确运行的
![image](https://github.com/silencht/SG-SLAM/assets/55626566/0d836568-2ef4-4479-b334-99d9386c73ff)

**Comment by silencht** [comment]
奇怪的错误。

在System.cc第62行（发生段错误）之前使用std::cout打印strSettingsFile.c_str()值，查看值是否正常。并与你的测试代码进行对比。

**Comment by QQQ300kuai** [comment]
我发现问题所在了，我电脑中是有opencv 4.2和3.3.1,修改了sg-slam的CMakeLists.txt为3.3.1，而cv_bridge使用的还是4.2，版本冲突造成，都改为3.3.1就能运行了。

但我又遇到另一个问题，rviz八叉树地图不能显示




![image](https://github.com/silencht/SG-SLAM/assets/55626566/90ef8131-4829-4140-ba01-9dfeeb0f5718)

`rviz -d /home/slam/SG-SLAM/src/sg-slam/Examples/rvizconfig.rviz  错误信息
`
![image](https://github.com/silencht/SG-SLAM/assets/55626566/fa512b54-7561-4f73-afea-5d5de44f6594)

**Comment by QQQ300kuai** [comment]
![image](https://github.com/silencht/SG-SLAM/assets/55626566/d5cba2aa-97e4-4762-af7d-f8f79e7192a2)

**Comment by silencht** [comment]
可能是ROS版本导致的tf/tf2迁移问题吧。
尝试把https://github.com/silencht/SG-SLAM/blob/7f34661d91f20a22995adad5813de7d964e859f3/src/octomap_server/launch/octomap.launch#L11 以及example目录下等与坐标系相关的/map均修改为map后再次编译运行。

**Comment by QQQ300kuai** [comment]
有帮助，八叉树地图可以显示，但语义对象度量地图无法显示，是哪个地方的/map没改的问题吗。
![image](https://github.com/silencht/SG-SLAM/assets/55626566/e35a41c2-b39c-491d-a61b-b7527169123e)

还有稠密点云图这样是正常的吗？运行的是gbd_dataset_freiburg3_walking_xyz序列
![image](https://github.com/silencht/SG-SLAM/assets/55626566/61366df9-b52d-4a8d-803b-5657335fd041)

**Comment by QQQ300kuai** [comment]
> 可能是ROS版本导致的tf/tf2迁移问题吧。 尝试把
> 
> https://github.com/silencht/SG-SLAM/blob/7f34661d91f20a22995adad5813de7d964e859f3/src/octomap_server/launch/octomap.launch#L11
> 
> 以及example目录下等与坐标系相关的/map均修改为map后再次编译运行。


是只有这两个地方的/map需要修改吗，我只修改了这两个地方，/map修改为了map
https://github.com/silencht/SG-SLAM/blob/7f34661d91f20a22995adad5813de7d964e859f3/src/sg-slam/Examples/rgbd_tum.cc#L207

https://github.com/silencht/SG-SLAM/blob/7f34661d91f20a22995adad5813de7d964e859f3/src/octomap_server/launch/octomap.launch#L13

**Comment by QQQ300kuai** [comment]
可以正常显示了。还有SG-SLAM/src/sg-slam/src/PointcloudMapping.cc里的/map没有修改，修改后语义对象度量地图和稠密地图都能显示。是ROS版本导致的tf/tf2迁移问题

在其他issue中看到了更详细的出现/map的位置https://github.com/silencht/SG-SLAM/issues/1#issuecomment-1587559048

想知道SG-SLAM是否可以用在室外场景中，作者有跑过KITTI等室外数据集吗？

**Comment by silencht** [comment]
> 还有稠密点云图这样是正常的吗？运行的是gbd_dataset_freiburg3_walking_xyz序列

看起来点云很稀疏，点云比较稀疏的原因可能是（你修改过的）分辨率等参数设置的比较低？正常效果可参考README中的视频链接。


> 想知道SG-SLAM是否可以用在室外场景中，作者有跑过KITTI等室外数据集吗？

这取决于你的RGB-D相机设备的工作环境支持情况，KITTI好像是双目数据集，我没有跑过它。
（因为ORB-SLAM系统对双目和RGB-D输入的处理差异比较小，故系统其实可以适配至双目，但这需要一定的工程量）
