### ISSUE TITLE
尝试通过VSCode进行Debug，但是报错std::bad_alloc

### ISSUE THREAD

**Issue by CloudsRL** [silencht/SG-SLAM#26]
您好，我希望在您的开源代码上进行修改和调试，但是通过终端输出中间过程比较繁琐，所以今天通过VSCode配置了Debug，也对SG-SLAM进行了重新编译（设定-DCMAKE_BUILD_TYPE=Debug）。但是在运行的时候，报错如下：
```
Input sensor was set to: RGB-D

Loading ORB Vocabulary. This could take a while...
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
[1] + Done                       "/usr/bin/gdb" --interpreter=mi --tty=${DbgTerm} 0<"/tmp/Microsoft-MIEngine-In-dxmzfnhj.4xu" 1>"/tmp/Microsoft-MIEngine-Out-vug03fmq.bmx"
```
对比一下程序，定位到System.cc的构造函数，可能是执行
```
    mpVocabulary = new ORBVocabulary();
```
这句话的时候报错。我上网查，这个bug的意思是内存不够，但是我的空余内存还有大约10GB，不应该是这个问题。

**请问作者有遇到过类似的情况吗，是如何解决的？或者作者是如何调试程序，检查中间变量的？
期盼得到回复**

**Comment by silencht** [comment]
没有遇到过这个情况。

当初ORB-SLAM程序设置Debug后运行过于缓慢，导致其与Release模式有明显的区别，所以我一般都是Release模式运行；我还尝试过使用Clion IDE运行Debug模式，但因为某些未知原因（可能是IDE占用内存太高），Clion在编译时容易卡死，所以这种调试方式也很快放弃。因为我对程序比较熟悉，所以重要的中间变量后期基本是通过打印的方式输出。

所以：1. 你可以尝试一下Clion（如果你对这种巨无霸IDE感兴趣的话）； 2. 检查VSCode的配置是否正确（因为VSCode正确配置C++工程确实是一个不太简单的任务，不过基于CMake的项目应该还好）（这些是我经常参考的配置文章：[VSCode之C++环境极简配置](https://zhuanlan.zhihu.com/p/554248108) 、[VSCode自带的debug和CMake tools插件的debug是两套逻辑吗](https://www.zhihu.com/question/471176365/answer/2386359912)）

另外，你是在哪个平台执行的代码，Windows吗？（我看log输出中含有`/tmp/Microsoft-MIEngine-Out-vug03fmq.bmx`字样）。

**Comment by CloudsRL** [comment]
感谢回复，我按照您参考的配置文章和一些网上的帖子调整了配置文件，已经成功的进入Debug状态了。
我是在Ubuntu18.04系统下执行的，不是windows。
