### ISSUE TITLE
ORB SLAM2架构升级的问题

### ISSUE THREAD

**Issue by larryzhz** [silencht/SG-SLAM#27]
非常感谢您的开发成果的分享，请问基于ORB SLAM2的系统鲁棒性如何？如何提高，比如容易升级到ORB SLAM3或其他么，感谢。

**Comment by silencht** [comment]
1. 基于ORB SLAM2的系统鲁棒性如何？
个人不成熟的看法。ORB-SLAM2虽然在论文中精度SOTA，但是实际中因为相机硬件（比如FOV小等）、环境（弱纹理、高动态等）等各种问题，非常容易LOST（尤其是大旋转场景）。ORB-SLAM3加入IMU之后情况有所改善，但依然有很多问题需要处理。鲁棒性只能说在学术界可用。
2. 容易升级到ORB SLAM3吗？
看个人对代码的熟悉程度。个人认为难度不高，但升级/调试的工作量还是有一些的。
