### ISSUE TITLE
调用CheckEpiLineDistToRmDynamicPoint(*it_cur, *it_pre, FundMat, 0.2)时的参数顺序问题

### ISSUE THREAD

**Issue by Effun-141** [silencht/SG-SLAM#28]
您好，首先感谢您的开源代码。我仔细阅读了您的代码，发现在Frame.cc中的565行：
`if(!CheckEpiLineDistToRmDynamicPoint(*it_cur, *it_pre, FundMat, 0.2))` 
这一句似乎将当前帧和前一帧的关键点参数顺序写反了，因为我注意到您在613行的`CheckEpiLineDistToRmDynamicPoint`函数的参数顺序是`const cv::Keypoint &kp1, const cv::Point2f &kp2`，根据您的函数内容和论文内容以及极线的定义，kp1应代表前一帧的特征点，kp2代表当前帧的特征点，那么前面的函数应修改为：
`if(!CheckEpiLineDistToRmDynamicPoint(*it_pre, *it_cur, FundMat, 0.2))`
且对应的`it_pre`和`it_cur`的类型也应作修改。
您觉得我这里的修改是否正确呢，还请您指教，谢谢！

**Comment by silencht** [comment]
时间有点久了，我凭印象说一下。
论文内容和代码内容稍微有点区别。这里好像是因为计算光流推特征点的时候，考虑到实时性等问题，是自当前帧向前一帧推光流拿到前一帧匹配特征。然后计算基础矩阵时，参数输入就是当前帧特征、前一帧特征。所以后面计算极线等内容的时候，是遵循的基础矩阵的计算顺序。所以论文是按正常思路在时间顺序上从前一帧到当前帧顺序计算，而代码实现是正好相反。
