### ISSUE TITLE
rviz显示报错

### ISSUE THREAD

**Issue by Ws1234567879789** [silencht/SG-SLAM#30]
[ERROR] [1717383594.172436817]: Error transforming pose 'Pose' from frame '/map' to frame 'map'
[ERROR] [1717383594.204727111]: Error transforming pose 'Pose' from frame '/map' to frame 'map'
[ERROR] [1717383594.252397908]: Error transforming pose 'Pose' from frame '/map' to frame 'map'
[ERROR] [1717383594.301022188]: Error transforming pose 'Pose' from frame '/map' to frame 'map'
[ERROR] [1717383594.348126390]: Error transforming pose 'Pose' from frame '/map' to frame 'map'

**Comment by silencht** [comment]
请参考https://github.com/silencht/SG-SLAM/issues/1
