### ISSUE TITLE
出现./Examples/sg_slam_tum: not found

### ISSUE THREAD

**Issue by MR-DKQ** [silencht/SG-SLAM#32]
出现了一个./Examples/sg_slam_tum: not found错误，感觉前面的编译没有错误，可能是哪方面出现了问题呢
<img width="338" alt="1721456202952" src="https://github.com/user-attachments/assets/4e159d95-1b75-4064-981b-c1f48373d9a4">

**Comment by silencht** [comment]
编译没有生成sg_slam_tum文件，应该是编译还存在问题。

**Comment by MR-DKQ** [comment]
感谢回答，确实是在编译catkin_make --pkg sg-slam这个时候出现了问题，多尝试几次就好了
