### ISSUE TITLE
每帧处理时间

### ISSUE THREAD

**Issue by hxy-x** [silencht/SG-SLAM#33]
作者您好，请问一下每帧处理时间代码是在哪里实现的，这个具体是在哪里查看呢

**Comment by silencht** [comment]
https://github.com/silencht/SG-SLAM/blob/a7046f00fed17c171c6f586e8bd2904fb0909b76/src/sg-slam/src/Frame.cc#L165

https://github.com/silencht/SG-SLAM/blob/a7046f00fed17c171c6f586e8bd2904fb0909b76/src/sg-slam/src/Tracking.cc#L235

诸如上述。

**Comment by hxy-x** [comment]
好的，好的，感谢作者
