### ISSUE TITLE
你好 我在尝试运行3D点云地图时 显示的效果是部分点云 这是为啥？

### ISSUE THREAD

**Issue by qinran123** [silencht/SG-SLAM#35]
![2024-10-30 17-52-37 的屏幕截图](https://github.com/user-attachments/assets/b0c9371f-c1b6-4d71-bc65-de98509e132f)

**Comment by silencht** [comment]
可能的原因：
1. 场景中有动态对象（人）的话 => 剔除此部分点云 => 点云输入减少
2. 为计算效率考虑，程序每次只处理关键帧点云，如果朝向某场景得关键帧数量稀疏 => 点云输入减少
3. 场景中可能含有高反射物体（玻璃，水），剔除了低质量的深度信息 => 点云输入减少
4. 高动态场景可能导致短暂丢失 => 关键帧缺失 => 点云输入减少

**Comment by qinran123** [comment]
我跑到 就是B站视频里的那个数据集

**Comment by silencht** [comment]
`/SG_SLAM/Global_Point_Clouds` topic 显示全局点云地图
`/SG_SLAM/Local_Point_Clouds` topic 显示当前关键帧点云

**Comment by qinran123** [comment]
/SG_SLAM/Global_Point_Clouds topic 显示全局点云地图 在RVIZ界面选择Global_Point_Clouds 没有显示点云
![Uploading 2024-11-10 16-09-27 的屏幕截图.png…]()

**Comment by qinran123** [comment]
![2024-11-10 16-09-27 的屏幕截图](https://github.com/user-attachments/assets/b711c21d-d711-4e7e-bdd6-2b7f153212b2)
在rviz界面 将Point_Clouds话题设为Global_Point_Clouds 没有显示点云

**Comment by silencht** [comment]
请提供camera.yaml参数或者程序启动过程的log以便查看问题。
