### ISSUE TITLE
师兄，ncnn路径问题还是没有解决，查看了之前的Issues还是没有解决

### ISSUE THREAD

**Issue by HAN-bo-nan** [silencht/SG-SLAM#38]
![2024-11-15 14-57-02屏幕截图](https://github.com/user-attachments/assets/8ccea56c-00e0-4c45-a01d-d314ffdd3e04)

**Comment by silencht** [comment]
尝试使用ncnnConfig.cmake文件的绝对路径呢？

**Comment by HAN-bo-nan** [comment]
已经解决了。把
`/home/hanbo/文档/SG-SLAM/src/sg-slam/Thirdparty/ncnn/build/install
/`
下的**bin,lib,include**三个文件夹拷贝到
`/usr/local/lib/ncnn
`
下就可以编译成功了
