### ISSUE TITLE
运行 ./run_tum_walking_xyz.sh 时没有反应

### ISSUE THREAD

**Issue by Justdo1t-lzw** [silencht/SG-SLAM#4]
代码编译通过，运行 ./run_tum_walking_xyz.sh 时没有反应
![image](https://github.com/silencht/SG-SLAM/assets/92515086/f127cbff-cd0b-4721-afaf-4149709a4826)
roslaunch octomap.launch 的时候显示： Nothing to publish, octree is empty
![image](https://github.com/silencht/SG-SLAM/assets/92515086/b387c106-6511-413f-bdc0-422a1bfe0266)
最新版本的代码中没有 transform.launch 从之前版本找的
rviz中也没有显示，是使用的 rvizconfig.rviz
这是我的topic
![image](https://github.com/silencht/SG-SLAM/assets/92515086/25cb3052-4976-4005-84f1-a63ff0fa586e)
求教有没有什么解决办法，感谢

**Comment by silencht** [comment]
新版本代码中不需要transform.launch，检查./run_tum_walking_xyz.sh命令的路径，对应路径是否有相关文件及数据集。或者直接手动输入命令测试。topic看起来没有问题。

**Comment by Justdo1t-lzw** [comment]
感谢您的帮助，我已经成功运行示例，我的错误是tum数据集没有使用associate.py同步，修改后运行效果看起来不错，感谢您的工作。

**Comment by MR-DKQ** [comment]
> associate.py

出现了一个./Examples/sg_slam_tum: not found错误，感觉前面的编译没有错误，可能是哪方面出现了问题呢
