### ISSUE TITLE
非常感谢！I didn't find a corresponding part of the specific modification

### ISSUE THREAD

**Issue by Sun173558** [silencht/SG-SLAM#41]
非常感谢！
我是用评论区的解决方式解决的，也就是把LoopClosing.cc错误的对应代码改成下面这样：
Eigen::aligned_allocator<std::pair<KeyFrame *const, g2o::Sim3> > > KeyFrameAndPose;
但我想请问一下，这种可能是由什么原因引起的呢？我在编译DynaSlam的时候也遇到了类似的错误

_Originally posted by @CloudsRL in https://github.com/silencht/SG-SLAM/issues/12#issuecomment-1754727525_

**Comment by silencht** [comment]
maybe you can check [this file: LoopClosing.h](https://github.com/silencht/SG-SLAM/blob/main/src/sg-slam/include/LoopClosing.h)

**Comment by Sun173558** [comment]
Display segment error, has been reset the system, there is no way to track, using gdb debugging results are as follows：




在 2024-12-04 10:34:45，"silencht" ***@***.***> 写道：

Closed #41 as completed.
