### ISSUE TITLE
真实数据集录制

### ISSUE THREAD

**Issue by Ws1234567879789** [silencht/SG-SLAM#42]
我使用D435i相机录制的真实场景的TUM格式的数据集，在建立八叉树地图时效果很差，无法分辨出物体特征，请问这是怎么回事

**Comment by silencht** [comment]
请提供运行视频以及终端日志

**Comment by Ws1234567879789** [comment]
请将你的邮箱给我下，谢谢

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年12月23日 09:24 |
| 收件人 | silencht/SG-SLAM ***@***.***> |
| 抄送人 | Ws1234567879789 ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [silencht/SG-SLAM] 真实数据集录制 (Issue #42) |

请提供运行视频以及终端日志

**Comment by silencht** [comment]
***@***.***



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年12月23日(周一) 上午9:34
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [silencht/SG-SLAM] 真实数据集录制 (Issue #42)




 请将你的邮箱给我下，谢谢
 
 ---- 回复的原邮件 ----
 | 发件人 | ***@***.***&gt; |
 | 发送日期 | 2024年12月23日 09:24 |
 | 收件人 | silencht/SG-SLAM ***@***.***&gt; |
 | 抄送人 | Ws1234567879789 ***@***.***&gt;,
 Author ***@***.***&gt; |
 | 主题 | Re: [silencht/SG-SLAM] 真实数据集录制 (Issue #42) |
 
 请提供运行视频以及终端日志

**Comment by Ws1234567879789** [comment]
你好，你的邮箱被官方隐藏了，全是*，您看可不可以发图片

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年12月23日 11:51 |
| 收件人 | silencht/SG-SLAM ***@***.***> |
| 抄送人 | Ws1234567879789 ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [silencht/SG-SLAM] 真实数据集录制 (Issue #42) |

***@***.***



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年12月23日(周一) 上午9:34
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [silencht/SG-SLAM] 真实数据集录制 (Issue #42)




请将你的邮箱给我下，谢谢

---- 回复的原邮件 ----
| 发件人 | ***@***.***&gt; |
| 发送日期 | 2024年12月23日 09:24 |
| 收件人 | silencht/SG-SLAM ***@***.***&gt; |
| 抄送人 | Ws1234567879789 ***@***.***&gt;,
Author ***@***.***&gt; |
| 主题 | Re: [silencht/SG-SLAM] 真实数据集录制 (Issue #42) |

请提供运行视频以及终端日志

**Comment by silencht** [comment]
你好，我 GitHub 主页里面有我的邮箱。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年12月23日(周一) 中午11:59
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [silencht/SG-SLAM] 真实数据集录制 (Issue #42)




 你好，你的邮箱被官方隐藏了，全是*，您看可不可以发图片
 
 ---- 回复的原邮件 ----
 | 发件人 | ***@***.***&gt; |
 | 发送日期 | 2024年12月23日 11:51 |
 | 收件人 | silencht/SG-SLAM ***@***.***&gt; |
 | 抄送人 | Ws1234567879789 ***@***.***&gt;,
 Author ***@***.***&gt; |
 | 主题 | Re: [silencht/SG-SLAM] 真实数据集录制 (Issue #42) |
 
 ***@***.***
 
 
 
 ---原始邮件---
 发件人: ***@***.***&amp;gt;
 发送时间: 2024年12月23日(周一) 上午9:34
 收件人: ***@***.***&amp;gt;;
 抄送: ***@***.******@***.***&amp;gt;;
 主题: Re: [silencht/SG-SLAM] 真实数据集录制 (Issue #42)
 
 
 
 
 请将你的邮箱给我下，谢谢
 
 ---- 回复的原邮件 ----
 | 发件人 | ***@***.***&amp;gt; |
 | 发送日期 | 2024年12月23日 09:24 |
 | 收件人 | silencht/SG-SLAM ***@***.***&amp;gt; |
 | 抄送人 | Ws1234567879789 ***@***.***&amp;gt;,
 Author ***@***.***&amp;gt; |
 | 主题 | Re: [silencht/SG-SLAM] 真实数据集录制 (Issue #42) |
 
 请提供运行视频以及终端日志

**Comment by Ws1234567879789** [comment]
我看了一下，没看到你的邮箱

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年12月23日 12:38 |
| 收件人 | silencht/SG-SLAM ***@***.***> |
| 抄送人 | Ws1234567879789 ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [silencht/SG-SLAM] 真实数据集录制 (Issue #42) |

你好，我 GitHub 主页里面有我的邮箱。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年12月23日(周一) 中午11:59
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [silencht/SG-SLAM] 真实数据集录制 (Issue #42)




你好，你的邮箱被官方隐藏了，全是*，您看可不可以发图片

---- 回复的原邮件 ----
| 发件人 | ***@***.***&gt; |
| 发送日期 | 2024年12月23日 11:51 |
| 收件人 | silencht/SG-SLAM ***@***.***&gt; |
| 抄送人 | Ws1234567879789 ***@***.***&gt;,
Author ***@***.***&gt; |
| 主题 | Re: [silencht/SG-SLAM] 真实数据集录制 (Issue #42) |

***@***.***



---原始邮件---
发件人: ***@***.***&amp;gt;
发送时间: 2024年12月23日(周一) 上午9:34
收件人: ***@***.***&amp;gt;;
抄送: ***@***.******@***.***&amp;gt;;
主题: Re: [silencht/SG-SLAM] 真实数据集录制 (Issue #42)




请将你的邮箱给我下，谢谢

---- 回复的原邮件 ----
| 发件人 | ***@***.***&amp;gt; |
| 发送日期 | 2024年12月23日 09:24 |
| 收件人 | silencht/SG-SLAM ***@***.***&amp;gt; |
| 抄送人 | Ws1234567879789 ***@***.***&amp;gt;,
Author ***@***.***&amp;gt; |
| 主题 | Re: [silencht/SG-SLAM] 真实数据集录制 (Issue #42) |

请提供运行视频以及终端日志

**Comment by silencht** [comment]
silencht[at]qq[dot]com
