### ISSUE TITLE
The display position of the semantic segmentation in the three-dimensional frame is different

### ISSUE THREAD

**Issue by 40526136** [silencht/SG-SLAM#6]
hello author
When the chair object is detected, but the position of the blue three-dimensional frame displayed in rviz is different in semantic segmentation, what should be done?
![2023-06-14 22-10-26 的螢幕擷圖](https://github.com/silencht/SG-SLAM/assets/52402399/a754cb6b-931b-488c-bc5f-afa8b39cd446)

**Comment by silencht** [comment]
Does it match the chair position of the octomap?
