### ISSUE TITLE
Problems encountered in running fr3_walking other datasets

### ISSUE THREAD

**Issue by wahaahaaaa** [silencht/SG-SLAM#7]
Hello author, when I run fr3_walking_xyz, when the camera deflects to the left, there is a situation where there are no feature points;
At the same time, when several other data sets are running, there is no running response and no window appears;
May I ask how to solve it, is it because of my computer configuration?

**Comment by silencht** [comment]
No feature points should be lost in the system track. There are several possible reasons for this, try adjusting the following parameter settings in tum3.yaml. See the README for a description of the parameters.

The appearance of no windows requires more information from you.

**Comment by wahaahaaaa** [comment]
TUM3.yaml文件完全使用的是作者你所给出的参数，运行所出现的问题我已录制，视频链接如下【fr3walking_xyz消失，track lost】 https://www.bilibili.com/video/BV1Uu4y1D7jJ/?share_source=copy_web&vd_source=1492107fa7aea466b4ba721f532497fe，问题出现在第20秒，track lost，望回复，感谢不尽！

**Comment by silencht** [comment]
Contact information has been provided in the video comments

**Comment by wahaahaaaa** [comment]
thank you!
